---
- name: Start and initialize MySQL, apply Flyway migrations
  hosts: localhost
  become: yes
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Ensure Flyway is installed and run migrations
      shell: |
        mkdir -p /opt/flyway
        cd /opt/flyway
        wget -q https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.1/flyway-commandline-9.22.1-linux-x64.tar.gz -O flyway.tar.gz
        tar -xzf flyway.tar.gz --strip-components=1
        ./flyway -url=jdbc:mysql://localhost:3306/subscribers -user=root -password=yourpassword migrate
      args:
        creates: /opt/flyway/flyway
